export const TOGGLE_INGREDIENT = 'TOGGLE_INGREDIENT';
export const CHANGE_PRICE = 'CHANGE_PRICE';
export const INGREDIENTS_RESET = 'INGREDIENTS_RESET';

export const POST_DATA_START = 'POST_DATA_START';
export const POST_DATA_SUCCEEDED = 'POST_DATA_SUCCEEDED';
export const POST_DATA_FAILED = 'POST_DATA_FAILED';
export const POST_DATA = 'POST_DATA';

export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCEEDED = 'FETCH_DATA_SUCCEEDED';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';
export const FETCH_DATA = 'FETCH_DATA';
